name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build
      - name: Setup .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=\$NODE_AUTH_TOKEN" > .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Debug
        run: |
          echo "Current directory: $(pwd)"
          echo ".npmrc exists: $(test -f .npmrc && echo 'yes' || echo 'no')"
          echo ".npmrc in home: $(test -f ~/.npmrc && echo 'yes' || echo 'no')"
          ls -la .npmrc || echo "No .npmrc in current dir"
          echo "Token length: ${#NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Verify auth
        run: npm whoami
      - name: Publish to npm
        run: npm publish --access public

  # Optional: deploy demo to gh-pages
  deploy-demo:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo